### PR TITLE
Added cipher guideline

### PR DESCRIPTION
**Pull request by riobard**

### CODE REVIEW

**Comment by madeye** [comment]
I suggest use "Not recommended" instead of "Deprecated" here.

Actually, we have no plan to deprecate stream ciphers.

**Comment by riobard** [comment]
We don't? OK, I'll update the PR.

**Comment by riobard** [comment]
But we're deprecating OTA, right?

**Comment by madeye** [comment]
Right, AEAD is purposed to replace OTA.

**Comment by madeye** [comment]
Cool. Let's merge this. Thanks!

**Pull request merged**
