### PR TITLE
Updated SIP002 FAQ

### PR DESCRIPTION
**Pull request by kimw**
Append a FAQ item,

> Q4: Why the tags with space is truncated?
> A4: White space is not legal in URI. It should be escaped. For example, `ss://...#shadowsocks server 1` (illegal URI) should be escaped into `ss://...#shadowsocks%20server%201` (legal URI).

### CODE REVIEW

**Comment by Mygod** [comment]
Or we can just say that it should follow the standard URI format instead of having a FAQ. Also this is a change to HTML.

**Comment by madeye** [comment]
@kimw Please also submit the change to the Markdown.

**Comment by kimw** [comment]
@madeye I didn't find the markdown file you're talk about. Can you point it out? Thanks.

**Comment by madeye** [comment]
@kimw Sorry, it'd be this page https://github.com/shadowsocks/shadowsocks-org/wiki/SIP002-URI-Scheme

**Comment by kimw** [comment]
@madeye OK, got it. The work is more simple, you known, it's really to hard to edit in HTML directly. I was so stupid.

sub-module...

AND...

Am I edit the Wiki enough? Or, should edit html & wiki both?

**Comment by kimw** [comment]
@madeye 
1. I can't edit the Wiki. Can you finish it?
2. see #95

**Comment by kimw** [comment]
I was totally wrong. The HTML will be overwrite by,
```
npm install -g grunt-cli
npm install
grunt
```

The right way to change SIP002 content should be **edit the Wiki file**.

According to I don't have the right to edit wiki, so I have nothing to do.

**Pull request merged**
