### PR TITLE
Refine doc for OTA

### PR DESCRIPTION
**Pull request by Mygod**

### CODE REVIEW

**Comment by Mygod** [comment]
Now why in the first place did we design our own authentication (which could have easily or already have gone wrong) instead of using authenticated encryption that has been tested, for example Salsa20-Poly1305 in NaCl, Chacha20-Poly1305 in Sodium or AES-256-GCM in both? (TODO: I'm just guessing that these have been tested or even academically proven. Are they really?)

I know there is a very old thread that has discussed this (https://github.com/shadowsocks/shadowsocks-chromeapp/issues/1#issuecomment-55698029) but the current OTA protocol also encapsulate every packet as well.

Another reason I've seen is performance (https://github.com/shadowsocks/shadowsocks/issues/330), which takes us back to the trade-off between security and performance. This is a valid argument but has anybody tested how much it will influence the performance? We should have some kind of benchmark to validate that. I contrived a script which works roughly as follow:

1. Listens on any port A, which copies from `/dev/null` endlessly to client sockets;
2. Get a packet from A, calculate connection delay t_1;
3. Keep getting b_1 bytes from A for T seconds;
4. Repeat 2-3 for N times;
5. Start a Shadowsocks client and a server that connects to localhost;
6. Connect to port A via Shadowsocks and get the first packet, calculate connection delay t'_1;
7. Keep getting b'_1 bytes for T seconds;
8. Repeat 6-7 for N times;
9. Calculate results.

```
Additional delay: average(t') - average(t)
Maximum throughput: average(b) / T
Shadowsocks throughput: average(b') / T
```

**Comment by v2ray** [comment]
My 2 cents for AES-GCM. Golang benchmark shows GCM (2.5gB/s) is 10 times faster than CFB(200MB/s). Despite other performance penalty in the pipeline, GCM should provide at least 1 gB/a throughout.

**Comment by wongsyrone** [comment]
Finally, on the right track. https://tonyarcieri.com/all-the-crypto-code-youve-ever-written-is-probably-broken

**Comment by wongsyrone** [comment]
Now libsodium supports three aead methods:

- aes256gcm
- chacha20poly1305
- xchacha20poly1305

According to materials, aes256gcm only performs quickly when having specialized hardware, e.g. AES-NI. It is not low-end-box-friendly, for example, routers.

> (see here and here for more info on Encrypt-and-MAC and MAC-then-Encrypt, with a focus on why one should avoid them)

> "people had been doing rather poorly when they tried to glue together a traditional (privacy-only) encryption scheme and a message authentication code (MAC)", in: M. Bellare; P. Rogaway; D. Wagner.

> "it is very easy to accidentally combine secure encryption schemes with secure MACs and still get insecure authenticated encryption schemes", in: T. Kohno; J. Viega & D. Whiting.

Other refs:
https://bristolcrypto.blogspot.com/2015/04/52-things-number-27-what-is-aead.html
https://en.wikipedia.org/wiki/Authenticated_encryption

**Comment by wongsyrone** [comment]
Just FYI. https://download.libsodium.org/libsodium/content/secret-key_cryptography/aead.html

> There are no plans to support non hardware-accelerated implementations of AES-GCM.
While AES is very fast on dedicated hardware, its performance on platforms that lack such hardware is considerably lower. Another problem is that many software AES implementations are vulnerable to cache-collision timing attacks.
ChaCha20 is also not sensitive to timing attacks.

**Comment by madeye** [comment]
Unfortunately, the motivation of OTA is patching the existed shadowsocks' stream ciphers, in order to defend attacks to the shadowsocks server. It is only applied on the request packets and designed to be HMAC before encrypting, which cannot ensure IND-CCA2 actually.

So, maybe we should remove the IND-CCA2 part in the description. @Mygod 

As mentioned by @wongsyrone, it's much better to follow existed AEAD instead of building the wheel ourselves. But shadowsocks is initially designed to be a simple and fast obfuscating SOCKS5 proxy with stream ciphers, And that's why we can implement it very easily and efficiently on the every known platform with different programming languages. 

I'm OK with adding AES-GCM and chacha20poly1305 as new ciphers (AEADs), if it's really necessary.

**Comment by wongsyrone** [comment]
If you want to use existed aes-gcm, I just found mbedtls is using different structs for cipher handling.

The current is mbedtls_cipher_context_t (https://github.com/ARMmbed/mbedtls/blob/master/include/mbedtls/cipher.h#L254), while gcm mode uses mbedtls_gcm_context (https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/gcm.h#L43) which includes cipher_context_t. If you want to keep current, you have to change definitions and keep a variable to determine if it is GCM or not. It will becomes really messy.

**Comment by wongsyrone** [comment]
I suggest adding chacha20poly1305 without aes-gcm.

**Comment by Mygod** [comment]
Reply to @wongsyrone: https://github.com/shadowsocks/shadowsocks-org/pull/29#issuecomment-272041380

In that case should we add AES-GCM? (btw all your replies doesn't show up in my inbox, I wonder why)

@madeye Let's add them and do some benchmark. We'll see. If they are not much slower than stream ciphers, I don't see a reason not to use them.

**Comment by madeye** [comment]
@Mygod It requires quite a lot of changes. Maybe we'd do that in Python version first.

**Comment by Mygod** [comment]
So it seems that OTA was added just to counteract the attack proposed [here](https://github.com/breakwa11/shadowsocks-rss/issues/38). I still think it's possible to perform a similar attack (to detect a Shadowsocks connection) for a man-in-the-middle by sending repeated XOR-ed packets to client on a connection for the current OTA protocol since OTA isn't enabled for server-to-client connections. Closing this PR for now.

**Comment by madeye** [comment]
BTW, For benchmark, we can directly use https://github.com/lparam/xSocks. It's exactly a shadowsocks-like protocol based on salsa208-poly1035 with IND-CCA2.

**Comment by Mygod** [comment]
@madeye Benchmark for xSocks can give us an approximate idea of the final results but I still think benchmark for Shadowsocks is necessary.

@wongsyrone It seems IND-CCA3 is just to used to say that it's equivalent to AE. Correct me if I'm wrong, I think IND-CCA2 implies IND-CCA3 so NM-CCA2 (which is equivalent to IND-CCA2) implies AE.

P.S. Our invention of OTA (which isn't a bright idea) may have caused [downstream ShadowsocksR to invent more authentication protocols by themselves](https://github.com/breakwa11/shadowsocks-rss/blob/115210f/ssr.md#协议特性) ([proof](https://github.com/shadowsocksr/shadowsocksr/commit/737b7d9890345f398c26c25fca328e64264a0637)).

**Comment by madeye** [comment]
@Mygod The interesting thing is when I implement chacha20-poly1035 in shadowsocks-libev, it becomes xSocks... The two protocols are just identical.

**Comment by wongsyrone** [comment]
I guess the purpose of breakwa11's shadowsocks attack scripts is to notify us OTA is not CCA as we claimed in the spec. It can be considered as a kind of MITM or CCA.

**Comment by wongsyrone** [comment]
BTW, I'm not an expert on cryptography, use existing facilities is a good idea to avoid pitfalls.

**Comment by Mygod** [comment]
@madeye Are you implying we should have used xSocks all along? 😅

**Comment by madeye** [comment]
@Mygod You got it... That's just my plan. If one day stream ciphers are not enough for bypassing the firewalls, I would switch to the "right" implementations (well known AEADs).

However, I don't think any known attacks to shadowsocks protocol is realistic. And please don't forget most of the traffic in shadowsocks protocol is TLS...

**Comment by madeye** [comment]
@wongsyrone The attacks from breakwa11 mostly target to our implementations instead of protocol. She studied every implementation's handshake characteristic and perform replay attack to identify the server. However, the characteristic she is using is based on statistics and depends on specific implementations, leading to a very large false positive.

**Comment by wongsyrone** [comment]
I think it due to lacking verification, thus replay attacks can be performed. If we do it right, the server-side should simply close connections and deny any further attempts.

**Comment by Mygod** [comment]
image

I imagine a possible attack could be performed on keep-alive HTTP connections. And migrating to well-tested AEADs also reduces the risk of future/unknown attacks.

**Comment by wongsyrone** [comment]
If I make it right, AEADs are sharing the same interface. https://tools.ietf.org/html/rfc5116

**Comment by madeye** [comment]
What about opening an issue with tags `pull request welcome` and `long term`? 😅

**Comment by madeye** [comment]
@Mygod And first create a SIP?

**Comment by Mygod** [comment]
Done. Go to #30 for further discussion.

**Pull request closed without merging**
