### PR TITLE
Add an open source iOS client app called Ladder

### PR DESCRIPTION
**Pull request by sheng**

### CODE REVIEW

**Comment by madeye** [comment]
It looks just a UI wrapper of NEKit.

**Comment by sheng** [comment]
@madeye 

Yep, a wrapper. Because I don't need to rewrite a SOCKS5 handler implementation. After all, the NEKit is also a wrapper, of the CocoaAsyncSocket, isn't it?

So I can't put it here right? Okay, I'll close this pull right now.

**Comment by madeye** [comment]
NEKit is not just a wrapper. It actually implements the protocol  of shadowsocks. 

https://github.com/zhuhaow/NEKit/blob/master/src/Socket/AdapterSocket/Factory/ShadowsocksAdapterFactory.swift

**Comment by sheng** [comment]
@madeye 

Ah, I think I got your point now. The protocol.

So if I implement the protocol myself, I can put it here, right? In fact, I just use NEKit to be able to implement the app quickly (NEKit is awesome, of course). I originally intended to implement the protocol myself because the NEKit was a bit big.

I'll add a TODO item in the README. When I have spare time, I will finish it.

**Pull request closed without merging**
